"""Initial migration

Revision ID: 201d5c1d8cfc
Revises: ce750e0a2ea0
Create Date: 2025-01-17 15:02:36.268326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '201d5c1d8cfc'
down_revision: Union[str, None] = 'ce750e0a2ea0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('price', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'price')
    # ### end Alembic commands ###
