"""Initial migration i addesd another thing

Revision ID: 203c3f114a9b
Revises: 3812bdb97a96
Create Date: 2025-01-21 19:50:09.901134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '203c3f114a9b'
down_revision: Union[str, None] = '3812bdb97a96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
