"""Initial migration i addesd another thing

Revision ID: 2a0a47a3ba0b
Revises: 0d6fe56f0991
Create Date: 2025-01-19 13:53:50.023101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a0a47a3ba0b'
down_revision: Union[str, None] = '0d6fe56f0991'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('to_do', 'in_progres', 'done', 'success', name='statustask'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_programmer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('programmer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['programmer_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('employees_position_id_fkey', 'employees', type_='foreignkey')
    op.create_foreign_key(None, 'employees', 'positions', ['position_id'], ['id'], onupdate='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.create_foreign_key('employees_position_id_fkey', 'employees', 'positions', ['position_id'], ['id'])
    op.drop_table('task_programmer')
    op.drop_table('tasks')
    # ### end Alembic commands ###
