"""Initial migration i addesd another thing

Revision ID: 3812bdb97a96
Revises: ad781113f79e
Create Date: 2025-01-21 19:35:13.326851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3812bdb97a96'
down_revision: Union[str, None] = 'ad781113f79e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('real_price', sa.String(length=100), nullable=False),
    sa.Column('pay_price', sa.String(length=100), nullable=False),
    sa.Column('date_paied', sa.DateTime(), nullable=False),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('from_student', 'from_project', name='incometype'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price_paid', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('date_paied', sa.DateTime(), nullable=False),
    sa.Column('employee_salary_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('from_student', 'from_project', name='incometype'), nullable=False),
    sa.Column('employee_salary', sa.Enum('employee_salary', 'for_office', 'smm_service', 'renting', 'other_expense', name='expensetype'), nullable=False),
    sa.ForeignKeyConstraint(['employee_salary_id'], ['employees.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'employees', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='unique')
    op.drop_table('expences')
    op.drop_table('incomes')
    # ### end Alembic commands ###
