"""Expense model some field become null

Revision ID: 5f34a49502f6
Revises: bccd5b5a3cd2
Create Date: 2025-01-24 17:47:23.073544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f34a49502f6'
down_revision: Union[str, None] = 'bccd5b5a3cd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expences', sa.Column('real_price', sa.String(), nullable=True))
    op.alter_column('expences', 'employee_salary_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expences', 'employee_salary_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('expences', 'real_price')
    # ### end Alembic commands ###
