"""Initial migration

Revision ID: 9283f28ab5f8
Revises: 0b42d8efde89
Create Date: 2025-01-18 18:37:37.383297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9283f28ab5f8'
down_revision: Union[str, None] = '0b42d8efde89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('operators_operator_type_id_fkey', 'operators', type_='foreignkey')
    op.create_foreign_key(None, 'operators', 'operator_type', ['operator_type_id'], ['id'], onupdate='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'operators', type_='foreignkey')
    op.create_foreign_key('operators_operator_type_id_fkey', 'operators', 'operator_type', ['operator_type_id'], ['id'])
    # ### end Alembic commands ###
