"""Initial migration i addesd another thing

Revision ID: ad781113f79e
Revises: 2a0a47a3ba0b
Create Date: 2025-01-19 18:21:56.223190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad781113f79e'
down_revision: Union[str, None] = '2a0a47a3ba0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
