"""Expense model some field become null

Revision ID: d05614b5c6f0
Revises: 5f34a49502f6
Create Date: 2025-01-24 18:16:09.070846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd05614b5c6f0'
down_revision: Union[str, None] = '5f34a49502f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expences', 'type',
               existing_type=postgresql.ENUM('from_student', 'from_project', name='incometype'),
               type_=sa.Enum('employee_salary', 'for_office', 'smm_service', 'renting', 'other_expense', name='expensetype'),
               existing_nullable=False)
    op.drop_column('expences', 'employee_salary')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expences', sa.Column('employee_salary', postgresql.ENUM('employee_salary', 'for_office', 'smm_service', 'renting', 'other_expense', name='expensetype'), autoincrement=False, nullable=False))
    op.alter_column('expences', 'type',
               existing_type=sa.Enum('employee_salary', 'for_office', 'smm_service', 'renting', 'other_expense', name='expensetype'),
               type_=postgresql.ENUM('from_student', 'from_project', name='incometype'),
               existing_nullable=False)
    # ### end Alembic commands ###
